Pressford.News.WebUI/Controllers/AdministrationController.cs
using System.Web.Mvc;

namespace Pressford.News.WebUI.Controllers
{
    public class AdministrationController : BaseAuthorisedController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Pressford.News.WebUI/Controllers/StatisticsController.cs
using System.Web.Mvc;

namespace Pressford.News.WebUI.Controllers
{
    public class StatisticsController : BaseAuthorisedController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Pressford.News.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pressford Consulting News</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_MenuBarPartial")
    <div class="container body-content" ng-app="pressfordNewsApp">
        <div class="page-header">
            <h2>@ViewBag.Title</h2>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Pressford Consulting</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @RenderSection("scripts", required: false)
</body>
</html>

Pressford.News.WebUI/Views/Shared/_MenuBarPartial.cshtml
@using Pressford.News.DomainModel.Entities
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index","Home")"><span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp;Pressford Consulting</a>
        </div>
        @if (ViewBag.IsAuthenticated)
        {
             using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new {id = "logoutForm"}))
             {
                 <div id="menuBar" class="collapse navbar-collapse">
                     <ul class="nav navbar-nav">
                         <li class="active"><a href="@Url.Action("Index","Home")">Articles</a></li>
                         <li><a href="@Url.Action("Index", "Statistics")">Statistics</a></li>
                         @if (ViewBag.UserRole == UserRoles.Administrator)
                         {
                             <li><a href="@Url.Action("Index", "Administration")">Administration</a></li>
                         }
                     </ul>
                     <ul class="nav navbar-nav navbar-right">
                         <li class="dropdown">
                             <a href="#" id="userDisplayName" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@ViewBag.UserDisplayName<span class="caret"></span></a>
                             <ul class="dropdown-menu">
                                 <li><a href="@Url.Action("MyProfile","Account")">My Profile</a></li>
                                 <li role="separator" class="divider"></li>
                                 <li><a href="javascript:document.getElementById('logoutForm').submit()">Log Out</a></li>
                             </ul>
                         </li>
                     </ul>
                 </div>
             }
        }
    </div>
</div>